=== huhongjun/mycop/cop-qiqu/model/input/jag.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!--W3C Schema 由 XMLSpy v2006 U 创建 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:complexType name="entityType">
		<xs:sequence>
			<xs:element name="xmltree" type="xmltreeType"/>
			<xs:element name="fieldlist" type="fieldlistType"/>
		</xs:sequence>
		<xs:attribute name="name" use="required"/>
		<xs:attribute name="display-name" use="required"/>
		<xs:attribute name="description" use="required"/>
		<xs:attribute name="root-package" use="required"/>
		<xs:attribute name="table-name" use="required"/>
		<xs:attribute name="primary-key" use="required"/>
		<xs:attribute name="primary-key-type" use="required"/>
		<xs:attribute name="primary-key-autoid"/>
		<xs:attribute name="is-composite" use="required"/>
		<xs:attribute name="is-association" use="required"/>
		<xs:attribute name="resoperationcode_edit"/>
		<xs:attribute name="resoperationcode_view"/>
		<xs:attribute name="querySQL" use="required"/>
		<xs:attribute name="ref-name" use="required"/>
	</xs:complexType>
	<xs:complexType name="fieldType" mixed="true">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="optionlist">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="option">
							<xs:complexType>
								<xs:attribute name="id" type="xs:string" use="required"/>
								<xs:attribute name="value" type="xs:string" use="required"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:choice>
		<xs:attribute name="name" use="required"/>
		<xs:attribute name="type" use="required"/>
		<xs:attribute name="column-name" use="required"/>
		<xs:attribute name="label" use="required"/>
		<xs:attribute name="required" type="xs:string" use="required"/>
		<xs:attribute name="sql-type" use="required"/>
		<xs:attribute name="jdbc-type" use="required"/>
		<xs:attribute name="primary-key" use="required"/>
		<xs:attribute name="auto-primary-key" type="xs:string" use="required"/>
		<xs:attribute name="foreign-key" type="xs:string" use="required"/>
		<xs:attribute name="validation-depends" type="xs:string" use="required"/>
		<xs:attribute name="validation-xml" type="xs:string" use="required"/>
		<xs:attribute name="ref-tablename" type="xs:string"/>
		<xs:attribute name="ref-columnname" type="xs:string"/>
		<xs:attribute name="tooltip" use="required"/>
		<xs:attribute name="length"/>
	</xs:complexType>
	<xs:complexType name="fieldlistType">
		<xs:sequence>
			<xs:element name="field" type="fieldType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="jag">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="app">
					<xs:complexType mixed="true">
						<xs:attribute name="name" use="required"/>
						<xs:attribute name="version" use="required"/>
						<xs:attribute name="description" use="required"/>
						<xs:attribute name="RootPackage" use="required"/>
						<xs:attribute name="LogFramework" use="required"/>
						<xs:attribute name="DateFormat" use="required"/>
						<xs:attribute name="TimestampFormat" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="config">
					<xs:complexType mixed="true">
						<xs:attribute name="author" use="required"/>
						<xs:attribute name="version" use="required"/>
						<xs:attribute name="company" use="required"/>
						<xs:attribute name="template-root" use="required"/>
						<xs:attribute name="Appservere" use="required"/>
						<xs:attribute name="BusinessTier" use="required"/>
						<xs:attribute name="useJava5" use="required"/>
						<xs:attribute name="useRelations" use="required"/>
						<xs:attribute name="useWebService" use="required"/>
						<xs:attribute name="useMock" use="required"/>
						<xs:attribute name="webTier" use="required"/>
						<xs:attribute name="serviceTier" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="path">
					<xs:complexType mixed="true">
						<xs:attribute name="ServiceOutput" use="required"/>
						<xs:attribute name="HibernateOutput" use="required"/>
						<xs:attribute name="EjbOutput" use="required"/>
						<xs:attribute name="WebOutput" use="required"/>
						<xs:attribute name="TestOutput" use="required"/>
						<xs:attribute name="JspOutput" use="required"/>
						<xs:attribute name="ConfigOutput" use="required"/>
						<xs:attribute name="MockOutput" type="xs:string" use="required"/>
						<xs:attribute name="swing_output" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="datasource">
					<xs:complexType mixed="true">
						<xs:attribute name="jndi-name" use="required"/>
						<xs:attribute name="mapping" use="required"/>
						<xs:attribute name="jdbc-driver" use="required"/>
						<xs:attribute name="jdbc-url" use="required"/>
						<xs:attribute name="user-name" use="required"/>
						<xs:attribute name="password" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="entitylist">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="entity" type="entityType"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="xmltreeType">
		<xs:attribute name="sql" use="required"/>
		<xs:attribute name="ref-nodeid" use="required"/>
		<xs:attribute name="cascade-column" use="required"/>
		<xs:attribute name="cascade-root" use="required"/>
		<xs:attribute name="rootname" use="required"/>
		<xs:attribute name="rootlabel" use="required"/>
	</xs:complexType>
</xs:schema>

=== huhongjun/mycop/trunk/model/input/jagModelFromPowerdesigner.xml
<?xml version="1.0" encoding="UTF-8"?>
<jag xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="D:/MyEclipseWork/workspace/QiQu-COP/model/input/jag.xsd">
<entitylist>
<entity name="DO_WORK_REPORT" display-name="工作汇报" table-name="DO_WORK_REPORT">
<fieldlist>
<field name="SERIAL_NUM" label="编号" required="1" sql-type="varchar(30)"/>
<field name="CREATE_DATE" label="日期 CREATE_DATE" sql-type="date"/>
<field name="USER_CODE" label="用户代码" sql-type="int"/>
<field name="BEGIN_TIME" label="开始时间 BEGIN_TIME" sql-type="date"/>
<field name="END_TIME" label="结束时间" sql-type="date"/>
<field name="RENDER" label="汇报人 RENDER" sql-type="varchar(20)"/>
<field name="CHECKER" label="审批 CHECKER" sql-type="varchar(20)"/>
<field name="CHECK_DATE" label="审批日期 CHECK_DATE" sql-type="date"/>
<field name="CONTENT" label="汇报内容 CONTENT" sql-type="blob"/>
<field name="SEND_FLAG" label="是否发送 SEND_FLAG" sql-type="int"/>
</fieldlist>
</entity>
<entity name="DO_IMPOWER" display-name="授权书" table-name="DO_IMPOWER">
<fieldlist>
<field name="SERIAL_NUM" label="编号" required="1" sql-type="varchar(30)"/>
<field name="CREATE_TIME" label="创建时间 CREATE_TIME" sql-type="date"/>
<field name="ACCEPTER" label="授权人 ACCEPTER" sql-type="varchar(20)"/>
<field name="PAYER" label="被授权人" sql-type="varchar(20)"/>
<field name="BEGIN_TIME" label="开始时间 BEGIN_TIME" sql-type="date"/>
<field name="END_TIME" label="结束时间" sql-type="date"/>
<field name="COMMENTS" label="授权说明" sql-type="varchar(60)"/>
<field name="NOTICE" label="通知人员" sql-type="varchar(2000)"/>
<field name="CONTENT" label="授权内容 CONTENT" sql-type="blob"/>
<field name="SEND_FLAG" label="是否发送 SEND_FLAG" sql-type="int"/>
</fieldlist>
</entity>
<entity name="DO_TEAM_LOG" display-name="日志团队设置" table-name="DO_TEAM_LOG">
<fieldlist>
<field name="SERIAL_NUM" label="编号" required="1" sql-type="varchar(30)"/>
<field name="USER_CODE" label="用户代码" sql-type="int"/>
<field name="TEAM_TYPE" label="团队类型" sql-type="int"/>
<field name="TEAM_MEMBER" label="团队成员" sql-type="varchar(1000)"/>
</fieldlist>
</entity>
<entity name="DO_WORK_LOG" display-name="工作日志" table-name="DO_WORK_LOG">
<fieldlist>
<field name="SERIAL_NUM" label="编号" required="1" sql-type="varchar(30)"/>
<field name="CREATE_TIME" label="创建时间 CREATE_TIME" sql-type="date"/>
<field name="DEPT_CODE" label="部门编码" sql-type="varchar(30)"/>
<field name="USER_CODE" label="用户代码" sql-type="int"/>
<field name="FILL_DATE" label="填写日期 FILL_DATE" sql-type="date"/>
<field name="LOG_CONTENT" label="日志内容 LOG_CONTENT" sql-type="blob"/>
</fieldlist>
</entity>
<entity name="DO_CALENDAR_ARRANGE" display-name="日程安排" table-name="DO_CALENDAR_ARRANGE">
<fieldlist>
<field name="SERIAL_NUM" label="SERIAL_NUM" required="1" sql-type="varchar(30)"/>
<field name="CALENDAR" label="CALENDAR" sql-type="date"/>
<field name="USER_CODE" label="USER_CODE" sql-type="int"/>
<field name="BEGIN_TIME" label="BEGIN_TIME" sql-type="date"/>
<field name="END_TIME" label="END_TIME" sql-type="date"/>
<field name="TASK_TYPE" label="TASK_TYPE" sql-type="int"/>
<field name="TASK_SUM" label="TASK_SUM" sql-type="varchar(60)"/>
<field name="TASK_CONTENT" label="TASK_CONTENT" sql-type="varchar(200)"/>
<field name="REMIND_FLAG" label="REMIND_FLAG" sql-type="int"/>
<field name="AWOKE_TIME" label="AWOKE_TIME" sql-type="int"/>
<field name="ARRANGE" label="ARRANGE" sql-type="varchar(20)"/>
</fieldlist>
</entity>
<entity name="DO_PERSONAL_TARGET" display-name="个人目标" table-name="DO_PERSONAL_TARGET">
<fieldlist>
<field name="SERIAL_NUM" label="编号" required="1" sql-type="varchar(30)"/>
<field name="USER_CODE" label="用户代码" sql-type="int"/>
<field name="CURRENT_YEAR" label="年 CURRENT_YEAR" sql-type="CHAR(4)"/>
<field name="CURRENT_MONTH" label="月 CURRENT_MONTH" sql-type="varchar(2)"/>
<field name="CURRENT_WORK" label="周 CURRENT_WORK" sql-type="CHAR(1)"/>
<field name="TARGET_TYPE" label="目标类型 TARGET_TYPE" sql-type="int"/>
<field name="DEPT_CODE" label="部门编码" sql-type="varchar(30)"/>
<field name="POST_CODE" label="岗位 POST_CODE" sql-type="varchar(30)"/>
<field name="CREATE_DATE" label="编制日期" sql-type="date"/>
<field name="TARGET_CONTENT" label="目标内容 TARGET_CONTENT" sql-type="blob"/>
<field name="AUDITOR" label="审核人 AUDITOR" sql-type="varchar(20)"/>
<field name="AUDIT_DATE" label="审核日期 AUDIT_DATE" sql-type="date"/>
<field name="AUDIT_FLAG" label="是否通过审核 AUDIT_FLAG" sql-type="int"/>
<field name="AUDIT_OPINION" label="审核意见 AUDIT_OPINION" sql-type="varchar(200)"/>
</fieldlist>
</entity>
<entity name="DO_TARGET_MANAGE" display-name="目标管理" table-name="DO_TARGET_MANAGE">
<fieldlist>
<field name="SERIAL_NUM" label="编号" required="1" sql-type="varchar(30)"/>
<field name="CURRENT_YEAR" label="年 CURRENT_YEAR" sql-type="CHAR(4)"/>
<field name="CURRENT_MONTH" label="月 CURRENT_MONTH" sql-type="varchar(2)"/>
<field name="CURRENT_WORK" label="周 CURRENT_WORK" sql-type="CHAR(1)"/>
<field name="TARGET_TYPE" label="目标类型 TARGET_TYPE" sql-type="CHAR(1)"/>
<field name="DEPT_CODE" label="部门编码" sql-type="varchar(30)"/>
<field name="USER_CODE" label="用户代码" sql-type="int"/>
<field name="CREATE_DATE" label="编制日期" sql-type="date"/>
<field name="AUDITOR" label="审核人 AUDITOR" sql-type="varchar(20)"/>
<field name="AUDIT_DATE" label="审核日期 AUDIT_DATE" sql-type="date"/>
<field name="AUDIT_FLAG" label="是否通过审核 AUDIT_FLAG" sql-type="int"/>
<field name="AUDIT_OPINION" label="审核意见 AUDIT_OPINION" sql-type="varchar(200)"/>
<field name="CHECK_FLAG" label="是否通过审批 CHECK_FLAG" sql-type="int"/>
<field name="CHECKER" label="审批人 CHECKER" sql-type="varchar(20)"/>
<field name="CHECK_DATE" label="审批日期 CHECK_DATE" sql-type="date"/>
<field name="CHECK_OPINION" label="审批意见 CHECK_OPINION" sql-type="varchar(200)"/>
<field name="TARGET_CONTENT" label="目标内容 TARGET_CONTENT" sql-type="blob"/>
</fieldlist>
</entity>
<entity name="DO_BBS_USER" display-name="论坛匿名用户表" table-name="DO_BBS_USER">
<fieldlist>
<field name="BBS_USER_CODE" label="BBS用户代码 BBS_USER_CODE" required="1" sql-type="varchar(20)"/>
<field name="NICKNAME" label="昵称 NICKNAME" required="1" sql-type="varchar(20)"/>
<field name="USER_ICON" label="用户图标 USER_ICON" sql-type="varchar(255)"/>
<field name="LAST_LOG_TIME" label="最后登陆时间 LAST_LOG_TIME" sql-type="date"/>
<field name="USER_STATE" label="用户状态 USER_STATE" required="1" sql-type="int"/>
<field name="USER_CODE" label="OA用户名称 USER_CODE" required="1" sql-type="int"/>
<field name="SEX_CODE" label="性别 SEX_CODE" sql-type="varchar(4)"/>
<field name="E_MAIL" label="电子邮件 E_MAIL" sql-type="varchar(30)"/>
<field name="HOME_PAGE" label="用户主页 HOME_PAGE" sql-type="varchar(100)"/>
</fieldlist>
</entity>
<entity name="DO_BBS_TOPICLIST" display-name="论坛话题表" table-name="DO_BBS_TOPICLIST">
<fieldlist>
<field name="SERIAL_NUM" label="话题编号" required="1" sql-type="varchar(30)"/>
<field name="TOPIC_NUM" label="主话题编号 TOPIC_NUM" required="1" sql-type="varchar(30)"/>
<field name="BBS_USER_CODE" label="BBS用户代码 BBS_USER_CODE" required="1" sql-type="varchar(20)"/>
<field name="CONTENT" label="内容 CONTENT" sql-type="varchar(3000)"/>
<field name="IP_ADDRESS" label="IP地址 IP_ADDRESS" sql-type="varchar(20)"/>
<field name="FILE_PATH" label="附件" sql-type="varchar(255)"/>
<field name="FILE_NAME" label="附件名称" sql-type="varchar(255)"/>
<field name="REPLY_DATE" label="回复时间 REPLY_DATE" sql-type="date"/>
<field name="AWOKE_FLAG" label="是否消息提醒 AWOKE_FLAG" required="1" sql-type="int"/>
<field name="IS_SHOW" label="是否显示 IS_SHOW" sql-type="int"/>
</fieldlist>
</entity>
<entity name="DO_BBS_SBOARD" display-name="论坛二级栏目表" table-name="DO_BBS_SBOARD">
<fieldlist>
<field name="SERIAL_NUM" label="二级栏目 SERIAL_NUM" required="1" sql-type="varchar(30)"/>
<field name="TBOARD_SERIAL" label="上级栏目编号 TBOARD_SERIAL" sql-type="varchar(30)"/>
<field name="SBOARD_NAME" label="栏目名称 SBOARD_NAME" required="1" sql-type="varchar(100)"/>
<field name="SBOARD_MASTER" label="栏目版主 SBOARD_MASTER" sql-type="varchar(20)"/>
<field name="ICON_FILE" label="栏目图标 ICON_FILE" sql-type="varchar(255)"/>
<field name="SBOARD_NOTE" label="栏目说明 SBOARD_NOTE" sql-type="varchar(200)"/>
<field name="SBOARD_STATE" label="栏目状态 SBOARD_STATE" sql-type="int"/>
</fieldlist>
</entity>
<entity name="DO_NETMEET" display-name="网络会议表" table-name="DO_NETMEET">
<fieldlist>
<field name="SERIAL_NUM" label="编号" required="1" sql-type="varchar(30)"/>
<field name="TITLE" label="主题 TITLE" sql-type="varchar(200)"/>
<field name="CALLER" label="召集 CALLER" sql-type="varchar(20)"/>
<field name="MASTER" label="主持 MASTER" sql-type="varchar(20)"/>
<field name="BEGIN_TIME" label="开始时间 BEGIN_TIME" sql-type="date"/>
<field name="END_TIME" label="结束时间" sql-type="date"/>
<field name="ATTENDS" label="出席人员 ATTENDS" sql-type="varchar(1000)"/>
<field name="ON_LINES" label="在线人员 ON_LINES" sql-type="varchar(1000)"/>
<field name="FINISH_FLAG" label="会议结束标志 FINISH_FLAG" sql-type="int"/>
<field name="RECORDER" label="记录" sql-type="varchar(20)"/>
<field name="SUMMARY" label="会议纪要 SUMMARY" sql-type="text"/>
<field name="FILE_PATH" label="附件" sql-type="varchar(255)"/>
<field name="FILE_NAME" label="附件名称" sql-type="varchar(255)"/>
<field name="AWOKE_FLAG" label="是否消息提醒 AWOKE_FLAG" required="1" sql-type="int"/>
<field name="BUILDING" label="是否归档 BUILDING" sql-type="int"/>
</fieldlist>
</entity>
<entity name="DO_NETMEET_CONTENT" display-name="网络会议内容" table-name="DO_NETMEET_CONTENT">
<fieldlist>
<field name="SERIAL_NUM" label="编号" required="1" sql-type="varchar(30)"/>
<field name="ORDER_ID" label="会议序号 ORDER_ID" required="1" sql-type="int"/>
<field name="USER_NAME" label="发言人 USER_NAME" sql-type="varchar(20)"/>
<field name="CONTENT" label="发言内容 CONTENT" sql-type="varchar(3000)"/>
<field name="USER_ICON" label="用户图标 USER_ICON" sql-type="varchar(255)"/>
<field name="FILE_PATH" label="附件" sql-type="varchar(255)"/>
<field name="FILE_NAME" label="附件名称" sql-type="varchar(255)"/>
</fieldlist>
</entity>
